version: "3.9"
services:
  nginx:
    container_name: note-nginx
    build: ./docker/nginx
    ports:
      - "8089:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html

  php-fpm:
    container_name: note-php-fpm
    build: ./docker/php
    volumes:
      - ./docker/php/php.ini:/usr/local/php/php.ini
      - ./src:/var/www/html

    ports:
      - "5173:5173"
  db:
    container_name: wk-db
    build: ./docker/mysql
    ports:
      - 3344:3306
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wk_portofolio
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
